<?php

/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function calendar_help($path, $arg) {
    $output = '';  //declare your output variable
    switch ($path) {
	case "admin/help#calendar":
	    $output = '<p>' . t("Organizes calendar events") . '</p>';
	    break;
    }
    return $output;
}

function calendar_menu() {
    $items = array();

    $items['admin/config/content/calendar'] = array(
	'title' => 'Calendar',
	'description' => 'Configuration for Calendar module',
	'page callback' => 'drupal_get_form',
	'page arguments' => array('calendar_form'),
	'access arguments' => array('access administration pages'),
	'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function calendar_form($form, &$form_state) {
    $form['calendar_id'] = array(
	'#type' => 'textfield',
	'#title' => t('Calendar ID'),
	'#default_value' => variable_get('calendar_id'),
	'#size' => 60,
	'#description' => t('The ID of the Google Calendar of P-Space.'),
	'#required' => TRUE,
    );

    $form['calendar_client_id'] = array(
	'#type' => 'textfield',
	'#title' => t('Client ID'),
	'#default_value' => variable_get('calendar_client_id'),
	'#size' => 60,
	'#description' => t('The Client ID of the service account.'),
	'#required' => TRUE,
    );

    $form['calendar_service_account'] = array(
	'#type' => 'textfield',
	'#title' => t('Service account name'),
	'#default_value' => variable_get('calendar_service_account'),
	'#size' => 60,
	'#description' => t('The service account name (or e-mail).'),
	'#required' => TRUE,
    );

    $form['calendar_key_path'] = array(
	'#type' => 'textfield',
	'#title' => t('Key path'),
	'#default_value' => variable_get('calendar_key_path'),
	'#size' => 60,
	'#description' => t('The private key\'s path (from drupal root)'),
	'#required' => TRUE,
    );

    return system_settings_form($form);
}

function calendarEventHandler() {
    require_once 'sites/all/libraries/google-api-php-client/src/Google_Client.php';
    require_once 'sites/all/libraries/google-api-php-client/src/contrib/Google_CalendarService.php';
    $client_id = variable_get('calendar_client_id');
    $calendar_id = variable_get('calendar_id');
    $service_account_name = variable_get('calendar_service_account');
    $key_path = variable_get('calendar_key_path');

    if (!isset($client_id) || !isset($calendar_id) || !isset($service_account_name) || !isset($key_path)) {
	header('Location: ' . base_path() . '/admin/config/content/calendar');
    } else if (empty($_GET['action']) && empty($_POST))
	displayCalendarEvents();
    else if (!empty($_GET['action'])) {
	if ($_GET['action'] == 'delete') {
	    deleteCalendarEvent($_GET['eid']);
	    header('Location: ' . variable_get('calendar_redirect_uri'));
	}
    } else if (isset($_POST['createEvent'])) {
	insertCalendarEvent($_POST);
	header('Location: ' . variable_get('calendar_redirect_uri'));
    } else if (isset($_POST['subscribeButton'])) {
	if ($_POST['subscribeButton'] == 'Εγγραφή')
	    insertNewSubscriber($_POST['e-mail']);
	else
	    deleteSubscriber($_POST['e-mail']);
	header('Location: ' . variable_get('calendar_redirect_uri'));
    }
}

function displayCalendarEvents() {

    $role = user_access('access administration pages');

    $events = getCalendarEvents();
    $eventListSize = sizeof($events);
    drupal_add_css(drupal_get_path('module', 'calendar') . '/css/calendar.css', NULL);
    drupal_add_js(drupal_get_path('module', 'calendar') . '/js/jquery-2.0.1.min.js');
    drupal_add_js(drupal_get_path('module', 'calendar') . '/js/jquery-ui.js');
    drupal_add_js(drupal_get_path('module', 'calendar') . '/js/scrolltopcontrol.js');
    drupal_add_js(drupal_get_path('module', 'calendar') . '/js/calendar.js');

    print "<div class='calendarContainer'>";

    if ($eventListSize == 0) {
	print "<h3>Δεν υπάρχουν καταχωρημένα γεγονότα στο ημερολόγιο!";
    } else {
	print "<table class='calendarTable'>
        <thead><th>Ημερομηνία</th><th>Event</th></thead>";
	for ($i = 0; $i < $eventListSize; $i++) {
	    $event = $events[$i];
	    printEvent($event, $role);
	}
	print "</table>";
    }
    print "</div>";
    if ($role == true) {
	include "createNewEvent.html";
    }

    include "subscribeForm.html";
}

function getCalendarEvents() {

    $calendarID = variable_get('calendar_id');

    $timeMax = $timeMin = getdate();
    $timeMax['year'] = $timeMax['year'] + 1;
    $timeMin['mday'] = $timeMin['mday'] - 1;
    $timeMax['RFC3339'] = $timeMax['year'] . '-' . $timeMax['mon'] . '-' . $timeMax['mday'] . 'T00:00:00Z';
    $timeMin['RFC3339'] = $timeMin['year'] . '-' . $timeMin['mon'] . '-' . $timeMax['mday'] . 'T00:00:00Z';

    $calendarParams = array(
	'orderBy' => 'startTime',
	'singleEvents' => 'true',
	'timeMin' => $timeMin['RFC3339'],
	'timeMax' => $timeMax['RFC3339']
    );

    $calendarService = initGoogleClient();
    $eventService = $calendarService->events;

    $eventResponse = $eventService->listEvents($calendarID, $calendarParams);

    return $eventResponse['items'];
}

function initGoogleClient() {

    $clientID = variable_get('calendar_client_id');
    $serviceAccountName = variable_get('calendar_service_account');

    $keyFile = variable_get('calendar_key_path');

    $client = new Google_Client();
    $client->setApplicationName("P-Space Google Calendar");


    if (isset($_SESSION['token'])) {
	$client->setAccessToken($_SESSION['token']);
    }

    $key = file_get_contents($keyFile);
    $client->setAssertionCredentials(new Google_AssertionCredentials(
	    $serviceAccountName, array('https://www.googleapis.com/auth/calendar', 'https://www.googleapis.com/auth/calendar.readonly'), $key)
    );

    $client->setClientId($clientID);

    //Save token in session
    if ($client->getAccessToken()) {
	echo 'Token: ' . $client->getAccessToken();
	$_SESSION['token'] = $client->getAccessToken();
    } else {
	echo 'getAccessToken error';
    }

    if ($client->isAccessTokenExpired()) {
	echo 'Token expired';
    }

    $calendarService = new Google_CalendarService($client);

    return $calendarService;
}

function parseDate($dateTime) {
    $englishWeekdays = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
    $greekWeekdays = array('Δευτέρα', 'Τρίτη', 'Τετάρτη', 'Πέμπτη', 'Παρασκευή', 'Σάββατο', 'Κυριακή');

    $englishMonths = array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec');
    $greekMonths = array('Ιαν', 'Φεβ', 'Μαρ', 'Απρ', 'Μαϊ', 'Ιουν', 'Ιουλ', 'Αυγ', 'Σεπ', 'Οκτ', 'Νοε', 'Δεκ');

    $weekday = $dateTime->format('l');
    $key = array_search($weekday, $englishWeekdays);
    $weekday = $greekWeekdays[$key];

    $day = $dateTime->format('d');
    $month = $dateTime->format('M');
    $key = array_search($month, $englishMonths);
    $month = $greekMonths[$key];

    $year = $dateTime->format('Y');
    $date = $weekday . ', ' . $day . ' ' . $month . ' ' . $year;
    return $date;
}

function parseTime($dateTime) {
    return $dateTime->format('H:i');
}

function printEvent($event, $isAdmin) {
    $dateString = parseDateTime($event['start'], $event['end']);

    print "<tr class='summary'><td>" . $dateString . "</td>
    <td><p>" . $event['summary'] . "</p>";

    print "<div class='details'>";
    if (isset($event['description'])) {
	print "<p><b>Περιγραφή</b></p><p>" . $event['description'] . "</p>";
    }
    if (isset($event['attendees'])) {
	$attendees = $event['attendees'];
	$totalGuests = sizeof($attendees);
	$guestsAccepted = 0;
	$guestsPending = 0;
	$guestsTentative = 0;
	$guestsDeclined = 0;

	for ($i = 0; $i < $totalGuests; $i++) {
	    $status = $attendees[$i]['responseStatus'];
	    switch ($status) {
		case 'needsAction':
		    $guestsPending++;
		    break;
		case 'declined':
		    $guestsDeclined++;
		    break;
		case 'tentative':
		    $guestsTentative++;
		    break;
		case 'accepted':
		    $guestsAccepted++;
		    break;
	    }
	}

	print "<h5>Στατιστικά</h5><p>Προσκεκλημένοι: " . $totalGuests . " Ναι: " . $guestsAccepted . " Οχι: " . $guestsDeclined . " Ίσως: " . $guestsTentative . " Καμία Απάντηση: " . $guestsPending . "</p>";
    }
    if ($isAdmin == true) {
	print "<p><a eid='" . $event ['id'] . "' onclick='deleteEvent(this)'>Διαγραφή του Γεγονότος</a></p>";
    }
    print "</div></td></tr>";
}

function parseDateTime($start, $end) {
    if (isset($start['date'])) {
	$startDate = date_create_from_format('Y-m-d', $start['date']);
	$endDate = date_create_from_format('Y-m-d', $end['date']);
	$startDate = parseDate($startDate);
	$endDate = parseDate($endDate);
	if ($startDate ==
		$endDate)
	    $date = $startDate;
	else
	    $date = $startDate . ' έως ' . $endDate;
    } else {
	$startDate = date_create_from_format('Y-m-d\TG:i:sP', $start['dateTime']);
	$endDate = date_create_from_format('Y-m-d\TG:i:sP', $end['dateTime']);
	$startTime = parseTime($startDate);
	$endTime = parseTime($endDate);
	$startDate = parseDate($startDate);
	$endDate = parseDate($endDate);
	$date = $startDate . ' στις ' . $startTime;
	if ($startDate == $endDate) {
	    $date .= ' έως ' . $endTime;
	}
	else
	    $date .= ' έως ' . $endDate . ' στις ' . $endTime;
    }
    return $date;
}

function deleteCalendarEvent($eventID) {
    $calendarID = variable_get('calendar_id');
    $calendarService = initGoogleClient();
    $calendarService->events->delete($calendarID, $eventID);
}

function getWeekdayBYDAY($date) {

    $englishWeekdays = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
    $codedWeekdays = array('MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU');

    $date = $date->format('l');
    $key = array_search($date, $englishWeekdays);
    return $codedWeekdays[$key];
}

function insertCalendarEvent($data) {

    $calendarID = variable_get('calendar_id');
    $calendarService = initGoogleClient();
    $event = new Google_Event();
    $event->setSummary($data['summary']);

    if (isset($data['loca
	    tion']))
	$event->setLocation($data['location']);
    if (isset($data['descrip
	    tion']))
	$event->setDescription($data['description']);


    $startDate = new Google_EventDateTime();
    $endDate = new Google_EventDateTime ();
    if (isset($data['fullDay'])) {
	$startDate->setDate($data['startDate']);
	$endDate->setDate($data['endDate']);
    } else {
	$startDate->setDateTime($data['startDate'] . "T" . $data['startTime'] . ":00");
	$endDate->setDateTime($data['endDate'] . "T" . $data['endTime'] . ":00");
    }

    $startDate->setTimeZone("Europe/Athens");
    $endDate->setTimeZone("Europe/Athens");
    $event->setStart($startDate);
    $event->setEnd($endDate);


    if (isset($data['recurrence'])) {
	$recurrenceDay = getWeekdayBYDAY(date_create_from_format('Y-m-d', $data['startDate']));
	$recurrenceRule = "RRULE:FREQ=" . $data['frequency'] . ";";

	if ($data['expiration'] == "after") {
	    $recurrenceRule .= "COUNT=" . $data['occurrences'] . ";";
	} else if ($data['expiration'] == 'until') {
	    $recurrenceEnd = date_create_from_format('Y-m-d', $data['recurrenceEnd']);
	    $recurrenceRule .= 'UNTIL=' . $recurrenceEnd->format('Ymd') . ';';
	}


	if ($data['frequency'] ==
		'DAILY')
	    $recurrenceRule.="INTERVAL=" . $data['repeat'];
	else if ($data['frequency'] == 'WEEKLY') {
	    $recurrenceRule.="INTERVAL=" . $data ['repeat'] . ';';
	    if (isset($data['days'])) {
		$days = implode(",", $data['days']);
		if (in_array($recurrenceDay, $data['days'
			]))
		    $recurrenceRule .= "BYDAY=" . $days;
		else
		    $recurrenceRule .= "BYDAY=" . $days . ',' . $recurrenceDay;
	    }
	    else
		$recurrenceRule .= "BYDAY=" . $recurrenceDay;
	} else {
	    $recurrenceRule.="INTERVAL=" . $data ['repeat'] . ';';
	    if ($data ['days'] ==
		    'weekday')
		$recurrenceRule .= 'BYDAY=1' . $recurrenceDay;
	    else if ($data ['days'] == 'monthday') {
		$day = date_create_from_format('Y-m-d', $data['startDate'])->format('d');
		$recurrenceRule.="BYMONTHDAY=" . $day;
	    }
	}


	$event->setRecurrence(array($recurrenceRule));
    }

    if (isset($data['invite'])) {
	$subscriptionFile = drupal_get_path('module', 'calendar') . "/contacts.xml";
	if (file_exists($subscriptionFile) && $xml = simplexml_load_file($subscriptionFile)) {

	    $i = 0;

	    if ($xml->count() > 0) {
		foreach ($xml->children() as $subscriber) {
		    $attendees[$i] = new Google_EventAttendee();
		    $attendees[$i]->setEmail((string) $subscriber);
		    $i++;
		}

		$event->attendees = $attendees;
	    }
	}
    }

    $event->setAttendeesOmitted(false);
    $event->setAnyoneCanAddSelf(true);
    $event->setGuestsCanInviteOthers(true);
    $event->setGuestsCanSeeOtherGuests(true);

    $optional = array();

    $eventService = $calendarService->events;
    $eventService->insert($calendarID, $event, $optional);
}

function insertNewSubscriber($email) {
    $subscriptionFile = drupal_get_path('module', 'calendar') . "/contacts.xml";
    if (!file_exists($subscriptionFile)) {
	$xml = new DOMDocument();
	$xml->appendChild($xml->createElement('list'));
	$xml->save($subscriptionFile);
    }
    $xml = simplexml_load_file($subscriptionFile);

    $mailExists = false;

    foreach ($xml->children() as $subscriber) {
	if ($subscriber == $email) {
	    $mailExists = true;
	    break;
	}
    }

    if ($mailExists == false) {
	$xml->addChild("subscriber", $email);
	$xml->asXML($subscriptionFile);
    }
}

function deleteSubscriber($email) {
    $subscriptionFile = drupal_get_path('module', 'calendar') . "/contacts.xml";
    if (!file_exists($subscriptionFile)) {
	return;
    }
    $xml = simplexml_load_file($subscriptionFile);

    foreach ($xml->children() as $subscriber) {
	if ($subscriber == $email) {
	    $dom = dom_import_simplexml($subscriber);
	    $dom->parentNode->removeChild($dom);
	    break;
	}
    }
    $xml->asXML($subscriptionFile);
    var_dump($xml);
}

function uberdust_event_handler($startDate, $endDate) {
    //$timezone = date_default_timezone_get();
    //print "The current server timezone is: " . $timezone;
    date_default_timezone_set('Europe/Athens');

    $current_datetime = new DateTime();
    print "Current time: " . $current_datetime->format('Y-m-d\TG:i:sP');

    if ($current_datetime < $startDate) {
	$diff = $startDate->diff($current_datetime);
	$time_left['years'] = $diff->format("%y");
	$time_left['months'] = $diff->format("%m");
	$time_left['days'] = $diff->format("%d");
	$time_left['hours'] = $diff->format("%h");
	$time_left['minutes'] = $diff->format("%i");
	$time_left['seconds'] = $diff->format("%s");

	print " Time left for the Event to start: " . $time_left ['years'] . " years," .
		$time_left ['months'] . " months," .
		$time_left ['days'] . " days," .
		$time_left ['hours'] . " hours," .
		$time_left['minutes'] . " minutes," .
		$time_left['seconds'] . " seconds";

	if (( $time_left ['years'] == 0) && ( $time_left ['months'] == 0) && ( $time_left ['days'] == 0)) {
	    if ($time_left ['hours'] <= 1) {
		//print "start the aircondition system";
		//uberdust_activate_nodes(aircondition, zone, 1);
		if ($time_left['minutes'] <= 10) {
		    //print "switch on the lights";
		    //uberdust_activate_nodes(light, zone, 1);
		}
	    }
	}
    } else if ($current_datetime >= $endDate) {
	$diff = $endDate->diff($current_datetime);
	$time_left['years'] = $diff->format("%y");
	$time_left['months'] = $diff->format("%m");
	$time_left['days'] = $diff->format("%d");
	$time_left['hours'] = $diff->format("%h");
	$time_left['minutes'] = $diff->format("%i");
	$time_left['seconds'] = $diff->format("%s");

	print " Event has reached end " . $time_left ['years'] . " years," .
		$time_left ['months'] . " months," .
		$time_left ['days'] . " days," .
		$time_left ['hours'] . " hours," .
		$time_left['minutes'] . " minutes," .
		$time_left['seconds'] . " seconds ago";

	if (( $time_left ['years'] == 0) && ( $time_left ['months'] == 0) && ( $time_left ['days'] == 0) && ( $time_left ['hours'] == 0)) {
	    if ($time_left['minutes'] >= 5) {
		//print "stop the aircondition system";
		//uberdust_activate_nodes(aircondition, zone, 0);
		//print "switch off the lights";
		//uberdust_activate_nodes(light, zone, 0);
	    }
	}
    }
}

function uberdust_activate_nodes($node, $zone, $status) {
    switch (node) {
	case aircondition:
// $.post( "http://uberdust.cti.gr/rest/testbed/1/node/urn:wisebed:ctitestbed:150.140.5.67/capability/urn:wisebed:node:capability:" +zone +"r/0/",status);
// http://uberdust.cti.gr/rest/testbed/5/node/urn:pspace:0x0ba/capability/urn:node:capability:light_switch/json/limit/10  <== auto gia p-space
	case lights:
//$.post( "http://uberdust.cti.gr/rest/testbed/1/node/urn:wisebed:ctitestbed:150.140.5.67/capability/urn:wisebed:node:capability:" +zone +"r/0/",status);
	default:
    }
}

