<?php
function power_sensor_show_all($show_controls){
$room = "CTI Room 0.I.1";
$node1Mac = "150.140.5.67";
$node1Type = "iSense";
$nodeUrn1 = "urn:wisebed:ctitestbed:";
$capability1 = "Consumption";
$maxRows = 10;
?>


    <?php
	if(empty($_GET['ip'])){	
		$status_raw=file_get_contents("http://uberdust.cti.gr/rest/testbed/1/status/raw");
		$line = explode("\n", $status_raw);
		for($i=0; $i<sizeof($line); $i++){
			$nodetype= explode("\t", $line[$i]);		
			if(isset($nodetype[3])&& ($nodetype[3]=="powerstrip")){	
				$node=explode(":", $nodetype[0]);
                echo ' <p>Choose one of the available power strips:</p> ';
				echo  '<p><a href="http://uberdust.cti.gr:81/uberdust/power?ip='.$node[3].'">'.$nodetype[0].'</a></p>';
			}	
		}			
	
	}
	else{ ?>
    <script>
    window.values = new Array();
    window.current = new Array();
    window.state=new Array();
    var max_value = new Array();
    var min_value = new Array();
    var minimum = 5000;
    var maximum = 0;



    <?php
        $capabilities = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/" . $nodeUrn1 . $_GET['ip'] . "/capabilities" );
        $line = explode("\n", $capabilities);
        $j=0;
    $k=0;
    $c=0;
        for($i=0; $i<sizeof($line); $i++){
        if(substr($line[$i],-1,1)=="i"){
                 $c++;
                 $id = substr($line[$i],-2,1);
                 $latestreading= file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "r/latestreading");
                 $row = explode("\t", $latestreading);
                 $indicator[$c]=$row[1];

            }
        if(substr($line[$i],-1,1)=="r"){
                 $k++;
                 $id = substr($line[$i],-2,1);
                 $latestreading= file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/" . $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "r/latestreading");
                 $row = explode("\t", $latestreading);
                 $status[$k]=$row[1];

            }

            if(substr($line[$i],-1,1)=="s"){
              $j++;?>
    values[<?php echo $j;?>] = [<?php
                        $id = substr($line[$i],-2,1);
                        $tabdelimited = file_get_contents("http://uberdust.cti.gr/rest/testbed/1/node/". $nodeUrn1 . $_GET['ip'] . "/capability/urn:wisebed:node:capability:" . $id . "s/latestreading");///tabdelimited/limit/maxrows
                        $lines = explode("\n", $tabdelimited, $maxRows);
                        unset($lines[count($lines) - 1]);
                        $firstRow = explode("\t", $lines[0]);
                        print( $firstRow[1] );
                        unset($lines[0]);
                        foreach ($lines as $thisLine) {
                            $row = explode("\t", $thisLine);
                            print(",".$row[1]);
                        }
                    ?>];


    <?php echo "current[$j] = $firstRow[1];";
    $current[$j]=$firstRow[1];?>
    //<?php echo "max_value[$j] = Math.max.apply(Math, values[$j]);"; ?>
    //<?php echo "min_value[$j] = Math.min.apply(Math, values[$j]);";?>
    //<?php echo "if(min_value[".$j."]< minimum){ mimimum = min_value[".$j."];} "; ?>
    //if(max_value[<?php echo $j;?>]> maximum){ maximum = 2 * max_value[<?php echo $j; ?>];}
   // if(min_value[<?php echo $j;?>]< minimum){ minimum = min_value[<?php echo $j; ?>];}

    <?php

        }//end if	==s
}// end of for loop
?>
    <?php
     $count=$j;
    for($j=1; $j<=$count; $j++){
    ?>


    $(function drawChart(){

        var chart<?php echo $j;?>;
        chart<?php echo $j;?> = new Highcharts.Chart({

                chart: {
                    renderTo: 'chart_div<?php echo $j;?>',
                    type: 'gauge',
                    plotBackgroundColor: '#222222',
                    plotBackgroundImage: null,
                    plotBorderWidth: 0,
                    plotShadow: false

                },

                title: {
                    text: 'Sensor <?php echo $j;?>'
                },

                pane: {
                    startAngle: -150,
                    endAngle: 150,
                    background: [
                        {
                            backgroundColor: {
                                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                                stops: [
                                    [0, '#FFF'],
                                    [1, '#333']
                                ]
                            },
                            borderWidth: 0,
                            outerRadius: '109%'
                        },
                        {
                            backgroundColor: {
                                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
                                stops: [
                                    [0, '#333'],
                                    [1, '#FFF']
                                ]
                            },
                            borderWidth: 1,
                            outerRadius: '107%'
                        },
                        {
                            // default background
                        },
                        {
                            backgroundColor: '#FFF',
                            borderWidth: 0,
                            outerRadius: '105%',
                            innerRadius: '103%'
                        }
                    ]
                },

                // the value axis
                yAxis: {
                    min: 0,
                    max: 1500,

                    minorTickInterval: 'auto',
                    minorTickWidth: 1,
                    minorTickLength: 10,
                    minorTickPosition: 'inside',
                    minorTickColor: '#666',

                    tickPixelInterval: 30,
                    tickWidth: 2,
                    tickPosition: 'inside',
                    tickLength: 10,
                    tickColor: '#666',
                    labels: {
                        step: 2,
                        rotation: 'auto'
                    },
                    title: {
                        text: 'mA'
                    },
                    plotBands: [{
                        from: 0,
                        to: 70,
                        color: '#A9A9A9	' // grey
                    },{
                        from: 70,
                        to: 800,
                        color: '#55BF3B' // green
                    }, {
                        from: 800,
                        to:1200 ,
                        color: '#DDDF0D' // yellow
                    }, {
                        from: 1200,
                        to: 1500,
                        color: '#DF5353' // red
                    }]
                },

                series: [{
                    name: 'Current Flow',
                    data: [window.current[<?php echo $j;?>]],
                    tooltip: {
                        valueSuffix: ' mA'
                    }
                }]
            },
            // Add some life
            function (chart<?php echo $j;?>){
                if (!chart<?php echo $j;?>.renderer.forExport) {
                    setInterval(function () {
                        var point<?php echo $j;?> = chart<?php echo $j;?>.series[0].points[0],
                            newVal<?php echo $j;?>,
                        // inc = Math.round((Math.random() - 0.5) * 20);

                            newVal<?php echo $j;?> = window.current[<?php echo $j; ?>];
                        point<?php echo $j;?>.update(parseFloat(newVal<?php echo $j;?>));
                    }, 3000);
                }
            });

        chart<?php echo $j;?>.setSize(230, 230, false);

    });


    <?php

    } // end for loop (drawchart)

for($j=1;$j<=$count;$j++){
    ?>
        connect("uberdust.cti.gr", "urn:wisebed:ctitestbed:150.140.5.67", "urn:wisebed:node:capability:<?php echo $j?>s",function(value2add){
            var val= new Array();
            var capability=" ";
            val=value2add.split(" ");
            capability=val[1].split(":");
            id=capability[4].split("");
            window.current[id[0]]=val[8];
        });
        connect("uberdust.cti.gr","urn:wisebed:ctitestbed:150.140.5.67","urn:wisebed:node:capability:<?php echo $j?>i",function(value2add){
            var val= new Array();
            var capability=" ";
            val=value2add.split(" ");
            capability=val[1].split(":");
            id=capability[4].split("");
            if(val[8]==1.0){
                 document.getElementById("led"+id[0]).src="/uberdust/sites/all/images/sensors/led-on-md.png";
            }else{
                 document.getElementById("led"+id[0]).src="/uberdust/sites/all/images/sensors/led-off-md.png";
            }
        });
        connect("uberdust.cti.gr","urn:wisebed:ctitestbed:150.140.5.67","urn:wisebed:node:capability:<?php echo $j?>r",function(value2add){
            var val= new Array();
            var capability=" ";
            val=value2add.split(" ");
            capability=val[1].split(":");
            id=capability[4].split("");
            if(val[8]==1.0){
                document.getElementById("myswitch"+id[0]).src="/uberdust/sites/all/images/sensors/newswitch1.png";
            }else{
                document.getElementById("myswitch"+id[0]).src="/uberdust/sites/all/images/sensors/newswitch0.png";
            }
        });
    <?php
        }
      ?>
    //





    //switch onclick
		function activate(zone,status){
			if (status==1.0){
				window.state[zone]=0.0;
				document.getElementById('myswitch'+zone+'').src="/uberdust/sites/all/images/sensors/newswitch0.png";
                $.post( "http://uberdust.cti.gr/rest/testbed/1/node/urn:wisebed:ctitestbed:150.140.5.67/capability/urn:wisebed:node:capability:" +zone +"r/0/",0);
			}
			else{
				window.state[zone]=1.0;
				document.getElementById('myswitch'+zone+'').src="/uberdust/sites/all/images/sensors/newswitch1.png";
                $.post( "http://uberdust.cti.gr/rest/testbed/1/node/urn:wisebed:ctitestbed:150.140.5.67/capability/urn:wisebed:node:capability:" +zone +"r/1/",1);
			}
		}
 </script>

	   <?php
                echo "<table aling='center'>";
                 for ($i = 1; $i <= $count; $i++) {
                 echo "<tr>";
                         echo "<td style='vertical-align:top;'>";
                        echo "<table style='vertical-align:top;'>";
                         echo "<tr><td>";
                                 $n='0x4ec';
                                if($show_controls==1){
                                     if($status[$i]==0.0)
                                            echo " <img src='/uberdust/sites/all/images/sensors/newswitch0.png' onclick = 'activate(".$i.",window.state[".$i."])' id= 'myswitch".$i."' alt='switch' height='80' width='80'/>";
                                     elseif($status[$i]==1.0)
                                            echo " <img src='/uberdust/sites/all/images/sensors/newswitch1.png' onclick = 'activate(".$i.",window.state[".$i."])' id= 'myswitch".$i."' alt='switch' height='80' width='80'/>";
                                }
                        echo "</td></tr>";
                        echo "<tr><td>";
                                 if($indicator[$i]==0.0)
                                     echo "<img id='led".$i."' src='/uberdust/sites/all/images/sensors/led-off-md.png' alt='off' width='65' height='65'>";
                                 elseif($indicator[$i]==1.0)
                                     echo "<img id='led".$i."' src='/uberdust/sites/all/images/sensors/led-on-md.png' alt='on' width='65' height='65'>";
                        echo "</td></tr>";
                        echo "</tr></table>";
                        echo "</td>";
                         echo "<td id='chart_div" . $i . "' style='width: 400px; margin: 0 0 0 0; ' ></td>";
                 echo "</tr>";
        }//for

	echo "</table>";
   }//if(empty($_GET)) 
}//function


